# Site settings
title: A data scientist diary
email: deroussel@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Natural data loveR

# Social icons
linkedin: denis-roussel-505a87b9
github: denrou

footer: © Taken theme

# Build settings
markdown: kramdown
